# Generated by Django 2.1.7 on 2019-04-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_author_text', models.CharField(max_length=200)),
                ('song_name_text', models.CharField(max_length=200)),
                ('song_kept', models.BooleanField(default=True)),
                ('song_added', models.BooleanField(default=False)),
                ('song_deleted', models.BooleanField(default=False)),
                ('origin_list_name_text', models.CharField(max_length=200)),
                ('origin_list_author_text', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(verbose_name='recent change date')),
            ],
        ),
    ]
