# Generated by Django 2.1.7 on 2019-04-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='origin_list_author_text',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_added',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_author_text',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_deleted',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_kept',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_name_text',
        ),
    ]
