# Generated by Django 2.1.7 on 2019-04-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createlist', '0002_auto_20190419_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('author_text', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(verbose_name='recent change date')),
            ],
        ),
    ]
